name: GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        include:
          - language: fr
            domain: recitsconfines.net

    steps:
    - uses: actions/checkout@v2.3.1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.3
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci

    - run: npm run generate
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_AUTO_ATTACH_COMMITS: ${{ secrets.SENTRY_AUTO_ATTACH_COMMITS }}
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_PUBLISH_RELEASE: ${{ secrets.SENTRY_PUBLISH_RELEASE }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        SENTRY_RELEASE_REPO: ${{ secrets.SENTRY_RELEASE_REPO }}
        API_URL: ${{ secrets.API_URL }}
        APP_LANG: ${{ matrix.language }}

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./dist
        cname: app.${{ matrix.domain }}
        publish_branch: master
        external_repository: recits-confines/${{ matrix.domain }}
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
