name: Preview Pages

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['15.x']

    steps:
    - uses: actions/checkout@v2.3.1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.5
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache
      uses: actions/cache@v2.1.4
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-

    - name: Install
      run: npm ci

    - run: npm run generate
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_AUTO_ATTACH_COMMITS: ${{ secrets.SENTRY_AUTO_ATTACH_COMMITS }}
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_PUBLISH_RELEASE: ${{ secrets.SENTRY_PUBLISH_RELEASE }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        SENTRY_RELEASE_REPO: ${{ secrets.SENTRY_RELEASE_REPO }}
        API_URL: ${{ secrets.PREVIEW_API_URL }}

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        cname: preview.recitsconfines.net
        force_orphan: true
